# Generated by Django 2.1.5 on 2019-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbangreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dmtinhtrangcx',
            fields=[
                ('matinhtrang', models.IntegerField(db_column='MaTinhTrang', primary_key=True, serialize=False)),
                ('tinhtrang', models.CharField(blank=True, db_column='TinhTrang', max_length=255, null=True)),
                ('ghichu', models.TextField(blank=True, db_column='GhiChu', null=True)),
            ],
            options={
                'db_table': 'DMTinhTrangCX',
                'managed': False,
            },
        ),
    ]
