# Generated by Django 2.1.5 on 2019-03-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbangreen', '0002_dmtinhtrangcx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dmchungloaicx',
            fields=[
                ('maloai', models.CharField(db_column='MaLoai', max_length=10, primary_key=True, serialize=False)),
                ('tenloai', models.CharField(blank=True, db_column='TenLoai', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DMChungLoaiCX',
                'managed': False,
            },
        ),
    ]
